name: Deploy
on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build Docker image
        run: |
          owner="${GITHUB_REPOSITORY_OWNER,,}"
          docker build -t "ghcr.io/$owner/kora-api:${GITHUB_SHA}" ./dev-ops/DeployReady

      - name: Push Docker image
        run: |
          owner="${GITHUB_REPOSITORY_OWNER,,}"
          docker push "ghcr.io/$owner/kora-api:${GITHUB_SHA}"

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4


